-- Beautiful HTML Email Templates - Part 1
-- Run this after removing the category constraint

-- First, remove the old constraint
ALTER TABLE email_templates DROP CONSTRAINT IF EXISTS email_templates_category_check;

-- Clear existing templates (optional - remove this line if you want to keep existing ones)
-- DELETE FROM email_templates;

-- Insert beautiful HTML templates
INSERT INTO email_templates (name, category, html_content) VALUES

-- WELCOME TEMPLATES
('Modern Welcome', 'Welcome', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Welcome</title></head><body style="margin:0;padding:0;background:#f8fafc;font-family:Arial,sans-serif"><div style="max-width:600px;margin:0 auto;background:#fff"><div style="background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);padding:60px 40px;text-align:center"><h1 style="color:#fff;font-size:32px;margin:0 0 16px 0;font-weight:bold">🎉 Welcome Aboard!</h1><p style="color:#fff;font-size:18px;margin:0;opacity:0.9">We''re thrilled to have you join our community</p></div><div style="padding:40px"><h2 style="color:#1f2937;font-size:24px;margin:0 0 20px 0">Hey {{name}},</h2><p style="color:#4b5563;font-size:16px;line-height:1.6;margin:0 0 24px 0">Welcome to our amazing community! You''re now part of something special. Here''s what you can expect:</p><div style="background:#f3f4f6;border-radius:12px;padding:24px;margin:24px 0"><div style="display:flex;align-items:center;margin-bottom:16px"><div style="width:40px;height:40px;background:#10b981;border-radius:50%;display:flex;align-items:center;justify-content:center;margin-right:16px"><span style="color:#fff;font-size:20px">✨</span></div><div><h3 style="color:#1f2937;font-size:18px;margin:0 0 4px 0">Exclusive Content</h3><p style="color:#6b7280;font-size:14px;margin:0">Access premium resources and tutorials</p></div></div><div style="display:flex;align-items:center;margin-bottom:16px"><div style="width:40px;height:40px;background:#3b82f6;border-radius:50%;display:flex;align-items:center;justify-content:center;margin-right:16px"><span style="color:#fff;font-size:20px">👥</span></div><div><h3 style="color:#1f2937;font-size:18px;margin:0 0 4px 0">Community Access</h3><p style="color:#6b7280;font-size:14px;margin:0">Connect with like-minded individuals</p></div></div><div style="display:flex;align-items:center"><div style="width:40px;height:40px;background:#f59e0b;border-radius:50%;display:flex;align-items:center;justify-content:center;margin-right:16px"><span style="color:#fff;font-size:20px">🚀</span></div><div><h3 style="color:#1f2937;font-size:18px;margin:0 0 4px 0">Priority Support</h3><p style="color:#6b7280;font-size:14px;margin:0">Get help when you need it most</p></div></div></div><div style="text-align:center;margin:32px 0"><a href="#" style="background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:#fff;text-decoration:none;padding:16px 32px;border-radius:8px;font-weight:bold;font-size:16px;display:inline-block">Get Started Now</a></div><p style="color:#6b7280;font-size:14px;line-height:1.6;margin:24px 0 0 0">Questions? Just reply to this email and we''ll help you out!</p></div><div style="background:#f9fafb;padding:24px;text-align:center;border-top:1px solid #e5e7eb"><p style="color:#9ca3af;font-size:12px;margin:0">© 2024 FlowMail. All rights reserved.</p></div></div></body></html>'),

('Elegant Onboarding', 'Welcome', '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background:#fafafa;font-family:Georgia,serif"><div style="max-width:600px;margin:0 auto;background:#fff;box-shadow:0 4px 6px rgba(0,0,0,0.1)"><div style="background:#1f2937;padding:40px;text-align:center"><div style="width:80px;height:80px;background:#fff;border-radius:50%;margin:0 auto 20px;display:flex;align-items:center;justify-content:center"><span style="font-size:32px">🌟</span></div><h1 style="color:#fff;font-size:28px;margin:0 0 12px 0">Welcome to Excellence</h1><p style="color:#d1d5db;font-size:16px;margin:0">Your journey to success starts here</p></div><div style="padding:48px 40px"><h2 style="color:#1f2937;font-size:24px;margin:0 0 24px 0;text-align:center">Hello {{name}},</h2><p style="color:#4b5563;font-size:16px;line-height:1.8;margin:0 0 32px 0;text-align:center">We''re delighted to welcome you to our exclusive community. You''ve just unlocked access to premium resources, expert insights, and a network of ambitious individuals.</p><div style="border:2px solid #e5e7eb;border-radius:12px;padding:32px;margin:32px 0;text-align:center"><h3 style="color:#1f2937;font-size:20px;margin:0 0 16px 0">What''s Next?</h3><div style="display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-top:24px"><div style="text-align:center"><div style="width:60px;height:60px;background:#dbeafe;border-radius:50%;margin:0 auto 12px;display:flex;align-items:center;justify-content:center"><span style="color:#3b82f6;font-size:24px">📚</span></div><h4 style="color:#1f2937;font-size:16px;margin:0 0 8px 0">Explore Resources</h4><p style="color:#6b7280;font-size:14px;margin:0">Browse our library of premium content</p></div><div style="text-align:center"><div style="width:60px;height:60px;background:#dcfce7;border-radius:50%;margin:0 auto 12px;display:flex;align-items:center;justify-content:center"><span style="color:#16a34a;font-size:24px">🤝</span></div><h4 style="color:#1f2937;font-size:16px;margin:0 0 8px 0">Join Community</h4><p style="color:#6b7280;font-size:14px;margin:0">Connect with fellow members</p></div></div></div><div style="text-align:center;margin:40px 0"><a href="#" style="background:#1f2937;color:#fff;text-decoration:none;padding:16px 40px;border-radius:6px;font-size:16px;font-weight:600;display:inline-block">Access Your Dashboard</a></div></div></div></body></html>'),